Unenduring [Необходимо проверить и исправить ошибки при запуске сервера, добавить к ним навыки]
VanillaStation14/VanillaStation pull request #60
Opened 2024-10-27 11:21 UTC by BogdanNovikov0207

## Описание PR

## Почему / Баланс

## Технические детали

## Медиа

## Требования

- [X] Я прочитал(а) и следую [Рекомендациям по оформлению Pull Request и Changelog](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] Я добавил(а) медиафайлы к этому PR или он не требует демонстрации в игре.

## Критические изменения

**Список изменений**

2024-11-08 20:11 UTC, thefuckmybrain requested changes
Компоненты и всякие прочие настройки находятся в файле - humanoid.yml
1) У гост ролей не может быть необходимого времени, удали это, иначе проект не соберётся
2) MobHumanModified - убери, расы настраиваются по-другому
3) у каждого прототипа должен быть свой **уникальный** id, у тебя же все обровцы - MobHumanUniqueERT
---
в общем, полностью убери MobHumanModified и всю работу веди в файле humanoid.yml, там у каждой роли минимум 2 прототипа:
1. entity (это прототип спавнера, а не самой сущности), там в целом ничего менять особо не нужно, разве что указать id прототипа сущности, которую будет спавнить спавнер
2. randomHumanoidSettings - это уже прототип сущности, которая будет взята из спавнера. Там можно указать блэклист для рас (по умолчанию дионы запрещены), и компоненты, которые будут выданы сущности поверх всех компонентов гуманоида + расы.

2024-11-08 20:14 UTC, thefuckmybrain commented
Если возможно, обрати внимание что там по несколько вариантов одного и того же обровца (лектор, ева, базовый) - сократи их число до 1 варианта, т.е. условно:
1 вариант обр инженеров
1 вариант обр уборщиков
1 вариант обр медиков 
итд,
иначе админ-панелька спавнера выглядит просто как каша с огромным числом обровцев

2024-11-09 16:34 UTC, thefuckmybrain commented
@BogdanNovikov0207
Исправил ошибки, теперь всё должно нормально работать.
1) Уменьши звук у ботинок и рации; они очень громкие.
2) Я удалил все прочие прототипы (отдельную еву, отдельный лектор) Теперь есть только: дед сквад, рхбзз, обр лидер и по одному виду обр каждого типа (обр уборщик, обр-инженер, итд) - в общем настрой им одежду. У них нет оружия и брони, а также у рхбзз нет твоих супер-крутых ботинок.

2024-11-10 12:13 UTC, BogdanNovikov0207 commented
@thefuckmybrain
все что просил - я сделал
снаряга у обр теперь есть, а у РХБЗЗ поменял бомжатскую двухстволку на бульдог. У священника я ничего по снаряге не менял, ибо использовать священника в отряде спецназа - как по мне бред. Дедов не менял, они и так ахуенные
у ботинок была ошибка со спрайтом во время переключения режима магниток, но эта проблема решена.
Не уверен только насчет звуков. Я вроде бы поменял числа, но разницы особой я не заметил, может быть потому что я глухой. У обуви звуки почти такие же, как и у ковбойских сапог

2024-11-19 20:55 UTC, merged