Ломать Плохое
VanillaStation14/VanillaStation pull request #76
Opened 2024-11-16 08:11 UTC by Bamgeglo1485

## Описание PR
Добавлена Хлорноватая кислота, Калиевая Соль Хлорноватой Кислоты, Красный Фосфор, Голубое Небо(Эфедронекс), еда в виде кристаллического эфедронекса, геймрул и гостроль варщиков метамфетамина(мелкие антаги).

## Почему / Баланс
Прикольная РПшная роль контрабандистов химиков, новый стимулятор с ускорением 1.5, но который не ускоряет восстановления стамины и дающий эффект наркорадуги, а также с длинной цепочкой варки с выделением углекислого газа, новая реакция взрыва красного фосфора и хлорноватой кислоты(изначально КСХК, но тогда варка мета была бы невозможной, из-за мгновенного взрыва.). В кристаллический эфедронекс можно влить 4u любого вещества, например порошок чили по рецепту Джесси Пинкмана.
Добавит большее разнообразие в геймплей и РП.

## Технические детали
Я устану всё перечислять, но главное: добавлена папка ваниллы в английскую локализацию, изменено пару прототипов для внедрения геймрула с варщиками.

## Медиа

https://github.com/user-attachments/assets/8f52a262-995d-4434-925c-c2dda17a4d2d

На остальные медиа мне лень.

## Требования

- [X] Я прочитал(а) и следую [Рекомендациям по оформлению Pull Request и Changelog](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] Я добавил(а) медиафайлы к этому PR или он не требует демонстрации в игре.
- [X] Я сварил(а) партию метамфетамина для колумбийского наркокартеля.

## Критические изменения
Ничего критического, вроде.

**Список изменений**

:cl:
add: Добавлены новые реагенты: хлорноватая кислота, калиевая соль хлорноватой кислоты, красный фосфор, Голубое Небо(Эфедронекс) и кристаллический эфедронекс. Подробнее о их рецептах в #изменения.
add: Добавлено новое событие с шаттлом нелегальных варщиков метамфетамина. Они являются мелкими антагонистами, их правила можно прочитать при нажатии кнопки участвия в лотерее.

2024-11-16 08:12 UTC, Bamgeglo1485 commented
опять ебут красными проверками

2024-11-17 02:27 UTC, thefuckmybrain commented
1. Будем ждать когда красные крестики станут зелеными галочками.
2. Не делай варщиков мета антагами, просто добавь их в пулл неопознанных шаттлов, они ведь геймплейно 1 в 1 такие же как и шаттл торговца чёрного рынка. (Id - blackmarketeer) да и разве подсаживать на наркотики преступление?
3. По самим веществам скажу когда починишь yml'ки (ошибки у тебя вызваны скорее всего либо лишними пробелами, либо может где-то отсутствует - или тип того)

2024-11-17 02:33 UTC, Bamgeglo1485 commented
> 1. Будем ждать когда красные крестики станут зелеными галочками.
> 2. Не делай варщиков мета антагами, просто добавь их в пулл неопознанных шаттлов, они ведь геймплейно 1 в 1 такие же как и шаттл торговца чёрного рынка. (Id - blackmarketeer) да и разве подсаживать на наркотики преступление?
> 3. По самим веществам скажу когда починишь yml'ки (ошибки у тебя вызваны скорее всего либо лишними пробелами, либо может где-то отсутствует символ «-» или тип того)

Там одна ошибка связана с картой paper, я в прототипе покопался, ничего не нашёл.

2024-11-17 02:39 UTC, thefuckmybrain commented
В дополнение к прошлому коменту:
Я прошарился по коду с телефона, поэтому я особо сильно не пон многих вещей, но вроде как ты создал отдельный ивент для них. В общем-то попробу взять за основу торговца черного рынка и прям сделай варщиков по такому же принципу как сделан торговец.
Ибо варщики как отдельный режим приведет к тому что эти варщики будут каждый раунд и их будет очень много, возможно по три штуки за одну смену.

+- Завтра с пк посмотрю получше код, в общем.

2024-11-17 02:42 UTC, Bamgeglo1485 commented
> В дополнение к прошлому коменту: Я прошарился по коду с телефона, поэтому я особо сильно не пон многих вещей, но вроде как ты создал отдельный ивент для них. В общем-то попробу взять за основу торговца черного рынка и прям сделай варщиков по такому же принципу как сделан торговец. Ибо варщики как отдельный режим приведет к тому что эти варщики будут каждый раунд и их будет очень много, возможно по три штуки за одну смену.
> 
> +- Завтра с пк посмотрю получше код, в общем.

Неа, я встроил варщиков в прототип потерянных шаттлов

2024-11-17 08:47 UTC, Bamgeglo1485 commented
что за невидимая ошибка

2024-11-18 04:12 UTC, Bamgeglo1485 commented
Я убрал пробелы, в игре нету никаких ошибок (только paper.yml), но этот CRLF проклял файлы

2024-11-20 02:48 UTC, thefuckmybrain commented
Попробуй опять обновить свой форк, я там довольно много чего пофиксил в основном репозитории

2024-11-20 11:08 UTC, Bamgeglo1485 commented
да я умный.

2024-11-20 11:36 UTC, Bamgeglo1485 commented
YEAH, SCIENCE!!

2024-11-20 19:33 UTC, thefuckmybrain commented
SERVER: 30,171s [INFO] loader: No user map found: /Maps/Shuttles/ShuttleEvent/cookers_shuttle.yml
 SERVER: 30,171s [INFO] loader: Loading Map: /Maps/Shuttles/ShuttleEvent/cookers_shuttle.yml
 SERVER: 30,203s [ERRO] map: Error in map file: found local entity UID '0' which does not exist.
 
 ошибки с cookers_shuttle.yml

2024-11-20 20:09 UTC, thefuckmybrain requested changes

2024-11-20 20:09 UTC, thefuckmybrain commented on Resources/Locale/en-US/vanilla/ghost/roles/ghost-role-component.ftl
Убери про то что они "нелегальные" больше подойдет "свободные"
и не стоит акцентировать на том что они варщики мета, они могут варить что-то другое

2024-11-20 20:09 UTC, thefuckmybrain commented on Resources/Locale/en-US/vanilla/prototypes/reagents/meta/narcotics.ftl
> +reagent-desc-blue-sky = Blue Sky, aka ephedronex. A potent drug and stimulant derived from methamphetamine. Due to the impurities involved in it, it has a blue color, but it is just as pure.
Скорее Ephedronex aka Blue Sky
```suggestion
reagent-desc-blue-sky = Ephedronex , aka Blue Sky. A potent drug and stimulant derived from methamphetamine. Due to the impurities involved in it, it has a blue color, but it is just as pure.
```

2024-11-20 20:09 UTC, thefuckmybrain commented on Resources/Locale/en-US/vanilla/prototypes/reagents/meta/narcotics.ftl
> +reagent-name-blue-sky = blue sky
```suggestion
reagent-name-blue-sky = Ephedronex 
```

2024-11-20 20:09 UTC, thefuckmybrain commented on Resources/Locale/ru-RU/vanilla/ghost/roles/ghost-role-component.ftl
> +ghost-role-information-cooker-name = нелегальный варщик метамфетамина
```suggestion
ghost-role-information-cooker-name = Свободный химик
```

2024-11-20 20:09 UTC, thefuckmybrain commented on Resources/Locale/ru-RU/vanilla/ghost/roles/ghost-role-component.ftl
> +ghost-role-information-cooker-name = нелегальный варщик метамфетамина
или типа того

2024-11-20 20:09 UTC, thefuckmybrain commented on Resources/Maps/Shuttles/ShuttleEvent/cookers_shuttle.yml
этот файл выбивает ошибки. Скорее всего как-то не так замаплен :c

2024-11-20 20:09 UTC, thefuckmybrain commented on Resources/Prototypes/GameRules/unknown_shuttles.yml
> +    preloadedGrid: Cookers_Shuttle
```
- type: entity
  id: UnknownShuttleCookers
  parent: BaseUnknownShuttleRule
  components:
  - type: StationEvent
    startAnnouncement: station-event-unknown-shuttle-incoming #!!
    weight: 8 # Это мелкие антаги
    earliestStart: 35
    minimumPlayers: 10
  - type: LoadMapRule
    preloadedGrid: Cookers_Shuttle
```
to:
```
- type: entity
  id: UnknownShuttleCookers
  parent: BaseUnknownShuttleRule
  components:
  - type: StationEvent
    startAnnouncement: station-event-unknown-shuttle-incoming #!!
  - type: LoadMapRule
    preloadedGrid: Cookers_Shuttle
```

2024-11-20 20:09 UTC, thefuckmybrain commented on Resources/Prototypes/Vanilla/Entities/Mobs/Player/ShuttleRoles/roles.yml
Импланты убираааем.
Помимо химии как будто стоит им выдать медицину (хотя бы 2 лвл) иначе они колоться шприцами не смогут

2024-11-20 20:09 UTC, thefuckmybrain commented on Resources/Prototypes/Vanilla/Entities/Mobs/Player/ShuttleRoles/settings.yml
> +      rules: ghost-role-information-nonantagonist-rules
```suggestion
      rules: ghost-role-information-freeagent-rules
```

2024-11-20 20:09 UTC, thefuckmybrain commented on Resources/Prototypes/Vanilla/Entities/Mobs/Player/ShuttleRoles/settings.yml
> +      rules: ghost-role-information-nonantagonist-rules
```suggestion
      rules: ghost-role-information-freeagent-rules
```

2024-11-20 20:09 UTC, thefuckmybrain commented on Resources/VanillaStation.lnk
ярлык проскочил

2024-11-21 07:06 UTC, Bamgeglo1485 commented
вроде всё сделал

2024-11-21 21:37 UTC, thefuckmybrain commented on Resources/Locale/ru-RU/vanilla/prototypes/reagents/meta/narcotics.ftl
> +reagent-desc-blue-sky = Эфедронекс, оно же "Голубое Небо". Сильнодействующий наркотик и стимулятор, производная от метамфетамина. Из-за задейстоваванных в нём примесей имеет голубой окрас, но он тако
```suggestion
reagent-desc-blue-sky = Эфедронекс, он же "Голубое Небо". Сильнодействующий наркотик и стимулятор, производная от метамфетамина. Из-за задейстоваванных в нём примесей имеет голубой окрас, но он такой же чистый.
```

2024-11-21 21:38 UTC, thefuckmybrain commented on Resources/Prototypes/Resources.lnk
вроде как это ярлык, который стоит удалить

2024-11-22 08:38 UTC, Bamgeglo1485 commented on Resources/Prototypes/Resources.lnk
как

2024-11-23 00:22 UTC, merged