Маппинг Кластера
VanillaStation14/VanillaStation pull request #9
Opened 2024-08-11 17:58 UTC by iAmScienceMan

## Описание PR
Добавлен тир в СБ, координально изменён отдел снабжения, исправлена комната парамедика, добавлен ТЭГ. Всё на карте Кластер.

**Медиа**
![image](https://github.com/user-attachments/assets/d22ed482-173a-41b0-8803-422074fae276)
![image](https://github.com/user-attachments/assets/71d77fde-6dd5-46c0-9fd0-a6a2dc4d9e53)
![image](https://github.com/user-attachments/assets/2bf7fac9-e4ce-485e-85c0-d83d33878b00)
![image](https://github.com/user-attachments/assets/a3f834f0-72f6-4093-bbd1-fc032092799c)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: iAmScienceMan
- add: Добавлен тир в СБ.
- add: Добавлен ТЭГ на Кластере.

:cl: TMG_HK
- tweak: Координально изменён отдел снабжения.

:cl: dogusu
- fix: Исправлена комната парамедика.

2024-08-12 20:18 UTC, thefuckmybrain requested changes
Уберите раундстартовый ящик пистолетов пулемётов из карго

2024-08-12 20:28 UTC, iAmScienceMan commented
> > Уберите раундстартовый ящик пистолетов пулемётов из карго
> 
> Он заспавнился рандомно, если конечно наш новенький не поставил его туда сам. Попробуй запустить карту опять и проверить, я сейчас не дома.

Вспомнил, там ящик СБ есть, но там всегда рандомный лут + его хер откроешь без доступов. Ну я уберу если надо, уже наверное завтра.

2024-08-13 21:16 UTC, thefuckmybrain commented
Также весь бриг нужно обернуть в укреплённые стены, в некоторых местах простые стены стоят вместо укреплённых

2024-08-15 19:48 UTC, iAmScienceMan commented
Всё, мерджи

2024-08-15 19:48 UTC, iAmScienceMan commented
А стоп

2024-08-15 19:53 UTC, iAmScienceMan commented
Всё, теперь 100% можно мерджить

2024-08-15 23:38 UTC, merged